# cloudbuild.yaml

steps:
  # Step 1: Set up buildx for multi-platform
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--use']

  # Step 2: Build and push the Docker image with buildx for the specified platform
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx', 'build',
      '--platform=linux/amd64',
      '-t', 'gcr.io/$PROJECT_ID/safecitydataservice:$COMMIT_SHA',
      '--push',
      '.'
    ]

  # Step 3: Add a longer delay to allow the image to propagate
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'sleep 30']  # Adjust the delay duration if necessary

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'safecitydataservice'
      - '--image=gcr.io/$PROJECT_ID/safecitydataservice:$COMMIT_SHA'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=ENVIRONMENT=stage,GCS_BUCKET_NAME=safecitycrimedata,GCP_PROJECT_ID=safecitydataservice'
      - '--set-secrets=SOCRATA_APP_TOKEN=SOCRATA_APP_TOKEN:latest'

substitutions:
  _COMMIT_SHA: '${SHORT_SHA}'

images:
  - 'gcr.io/$PROJECT_ID/safecitydataservice:$COMMIT_SHA'
