version: "3.8"

services:
  safecitydataservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=docker
    ports:
      - "${PORT:-8000}:80"
    env_file:
      - .env
    volumes:
      - ./safe-city-walk-0188a532813e.json:/app/google-credentials.json:ro
      # - ./env.yaml:/app/env.yaml:ro
    stdin_open: true # Enable stdin
    tty: true # Allocate a pseudo-TTY

volumes:
  google-credentials:
