version: "3.8"

services:
  safecitydataservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ENVIRONMENT=local
    env_file:
      - .env.${ENVIRONMENT-local}
    volumes:
      - ./safe-city-walk-0188a532813e.json:/app/google-credentials.json:ro
    stdin_open: true # Enable stdin
    tty: true # Allocate a pseudo-TTY

volumes:
  google-credentials:
