version: "3.8"

services:
  safecitydataservice_docker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=docker # Set ENV to 'docker'
    env_file:
      - .env.docker
    ports:
      - "8000:8080" # 8080 is the host port (8080 in localhost is occupied by another service), 8080 is the container port
    volumes:
      - ./safecitydataservice.json:/app/google-credentials.json:ro # Mount credentials as read-only
    stdin_open: true # Enable stdin (useful for debugging)
    tty: true # Allocate a pseudo-TTY

volumes:
  google-credentials:
    driver: local # Optional: local volume driver for clarity
