name: Deploy to Cloud Run

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v4
      with: 
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker to Google Container Registry
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{  secrets.PROJECT_ID }}/safecitydataservice .

    - name: Push Docker image to Google Container Registry
      run: docker push gcr.io/${{ secrets.PROJECT_ID }}/safecitydataservice

    - name: Deplot to Cloud run
      run: gcloud run deploy safecitydataservice --image gcr.io/${{ secrets.PROJECT_ID }}/safecitydataservice --region us-central1 --allow-unauthenticated --service-account safecitydataservice-sa@$PROJECT_ID.iam.gserviceaccount.com
